package Principal;

import java.awt.Image;
import java.awt.Toolkit;
import java.io.IOException;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import java.util.Timer;
import java.util.TimerTask;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.sound.sampled.AudioSystem;
import javax.sound.sampled.Clip;
import javax.sound.sampled.LineUnavailableException;
import javax.sound.sampled.UnsupportedAudioFileException;

/**
 *
 * @author Samuel Boada
 * @author Marcos De Andrade
 * @author Alberto Pereira
 */

public class VentanaZelzar extends javax.swing.JFrame {

    private Toolkit tk;
    private int X, Y;
    /*------------------------------------Audio------------------------------------*/
    public Clip clip;
    public String ruta = "/Audio/";

    /*------------------------------------Mensajes------------------------------------*/
    private VentanaAdvertenciaSalir mensajeAdvertencia;
    private VentanaAyuda mensajeAyuda;
    private VentanaZelzarTarjeta ventanaTarjeta;
    /*------------------------------------Imagenes------------------------------------*/
    //Imagen Opening
    private ImageIcon Opening1, Opening2;
    //Imagen boton Cerrar Blanco
    private ImageIcon CerrarBlanco_0, CerrarBlanco_1;
    //Imagen boton Ayuda
    private ImageIcon Ayuda_0, Ayuda_1;

    /*------------------------------------Metodos------------------------------------*/
    public VentanaZelzar() throws IOException {
        initComponents();
        mensajeAdvertencia = new VentanaAdvertenciaSalir();
        mensajeAyuda = new VentanaAyuda();
        ventanaTarjeta = new VentanaZelzarTarjeta();

        tk = Toolkit.getDefaultToolkit();
        X = (int) (tk.getScreenSize().getWidth());
        Y = (int) (tk.getScreenSize().getHeight());

        this.setLocationRelativeTo(null);

        tarjeta.setEnabled(false);

        //Escalar y Establecer la Imagen de Fondo Principal
        Opening1 = new ImageIcon("src/Imagenes_Wallpapers/ZelzarSinTarjeta-0.png");
        this.fondo.setIcon(new ImageIcon(Opening1.getImage().getScaledInstance(fondo.getWidth(), fondo.getHeight(), Image.SCALE_SMOOTH)));

        //Escalar y escoger Boton Cerrar
        CerrarBlanco_0 = new ImageIcon("src/Imagenes_Botones/CerrarBlanco-0.png");
        CerrarBlanco_1 = new ImageIcon("src/Imagenes_Botones/CerrarBlanco-1.png");
        this.cerrar.setIcon(new ImageIcon(CerrarBlanco_0.getImage().getScaledInstance(45, 65, Image.SCALE_SMOOTH)));
        this.cerrar.setRolloverIcon(new ImageIcon(CerrarBlanco_1.getImage().getScaledInstance(50, 70, Image.SCALE_SMOOTH)));

        //Escalar y escoger Boton Ayuda
        Ayuda_0 = new ImageIcon("src/Imagenes_Botones/Ayuda-0.png");
        Ayuda_1 = new ImageIcon("src/Imagenes_Botones/Ayuda-1.png");
        this.ayuda.setIcon(new ImageIcon(Ayuda_0.getImage().getScaledInstance(44, 65, Image.SCALE_SMOOTH)));
        this.ayuda.setRolloverIcon(new ImageIcon(Ayuda_1.getImage().getScaledInstance(50, 70, Image.SCALE_SMOOTH)));

        //Crea el segundo Fondo a usar
        Opening2 = new ImageIcon("src/Imagenes_Wallpapers/ZelzarConTarjeta-0.png");

        Audio("SonidoCantoGregoriano1");

        //LLama al Metodo para Cambiar el Fondo
        CambiarFondo();

        this.repaint();
    }

    
    public void Audio(String archivo) {
        try {
            clip = AudioSystem.getClip();
            clip.open(AudioSystem.getAudioInputStream(getClass().getResourceAsStream(ruta + archivo + ".wav")));
            clip.start();
        } catch (IOException e) {
        } catch (LineUnavailableException e) {
        } catch (UnsupportedAudioFileException e) {
        }
    }

    //Metodo para Hacer que la tarjeta aparezca
    public void CambiarFondo() {

        int velocidad = 4500; //milisegendos
        Timer timer;
        TimerTask tarea;

        tarea = new TimerTask() {
            @Override
            public void run() {
                fondo.setIcon(new ImageIcon(Opening2.getImage().getScaledInstance(fondo.getWidth(), fondo.getHeight(), Image.SCALE_SMOOTH)));
                tarjeta.setEnabled(true);
                //Audio("SonidoTarjeta1");
            }
        };
        timer = new Timer();
        timer.schedule(tarea, velocidad);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lean = new javax.swing.JPanel();
        tarjeta = new javax.swing.JButton();
        ayuda = new javax.swing.JButton();
        cerrar = new javax.swing.JButton();
        fondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);

        lean.setPreferredSize(new java.awt.Dimension(580, 700));
        lean.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tarjeta.setBorder(null);
        tarjeta.setBorderPainted(false);
        tarjeta.setContentAreaFilled(false);
        tarjeta.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        tarjeta.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        tarjeta.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                tarjetaMouseEntered(evt);
            }
        });
        tarjeta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tarjetaActionPerformed(evt);
            }
        });
        lean.add(tarjeta, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 610, 180, 50));

        ayuda.setBorder(null);
        ayuda.setBorderPainted(false);
        ayuda.setContentAreaFilled(false);
        ayuda.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        ayuda.setFocusPainted(false);
        ayuda.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        ayuda.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                ayudaMouseEntered(evt);
            }
        });
        ayuda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ayudaActionPerformed(evt);
            }
        });
        lean.add(ayuda, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 600, 60, 80));

        cerrar.setBorder(null);
        cerrar.setBorderPainted(false);
        cerrar.setContentAreaFilled(false);
        cerrar.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        cerrar.setFocusPainted(false);
        cerrar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        cerrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                cerrarMouseEntered(evt);
            }
        });
        cerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cerrarActionPerformed(evt);
            }
        });
        lean.add(cerrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 20, 60, 80));

        fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes_Wallpapers/ZelzarSinTarjeta-0.png"))); // NOI18N
        fondo.setPreferredSize(new java.awt.Dimension(580, 700));
        lean.add(fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 580, 700));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lean, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lean, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cerrarActionPerformed
        setVisible(false);
    }//GEN-LAST:event_cerrarActionPerformed

    private void ayudaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ayudaActionPerformed
        this.mensajeAyuda.setVisible(true);
    }//GEN-LAST:event_ayudaActionPerformed

    private void tarjetaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tarjetaActionPerformed
        this.ventanaTarjeta.setVisible(true);
    }//GEN-LAST:event_tarjetaActionPerformed

    private void tarjetaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tarjetaMouseEntered
        Audio("SonidoBoton1");
    }//GEN-LAST:event_tarjetaMouseEntered

    private void ayudaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ayudaMouseEntered
        Audio("SonidoBoton1");
    }//GEN-LAST:event_ayudaMouseEntered

    private void cerrarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cerrarMouseEntered
        Audio("SonidoBoton1");
    }//GEN-LAST:event_cerrarMouseEntered

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaZelzar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaZelzar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaZelzar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaZelzar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new VentanaZelzar().setVisible(true);
                } catch (IOException ex) {
                    Logger.getLogger(VentanaZelzar.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ayuda;
    private javax.swing.JButton cerrar;
    private javax.swing.JLabel fondo;
    private javax.swing.JPanel lean;
    private javax.swing.JButton tarjeta;
    // End of variables declaration//GEN-END:variables
}
